server:
  servlet:
    context-path: /api

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: gigstracker
  
  datasource:
    url: jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:6543/postgres?prepareThreshold=0
    username: postgres.${PROJECT_ID}
    password: ${DATABASE_PASSWORD}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 3
  
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${PROJECT_ID}.supabase.co/auth/v1
          jwk-set-uri: https://${PROJECT_ID}.supabase.co/auth/v1/.well-known/jwks.json

logging:
  level:
    org.springframework.security: DEBUG
    org.springframework.security.oauth2: DEBUG
